Add build script
slp/capng pull request #2
Opened 2022-03-04 15:24 UTC by germag

This build script allows capng to be linked statically
to libcap-ng and/or select the library's location.
To set the link type the build script will check the
env. variable LIBCAPNG_LINK_STATIC, if its value is
'1' or 'true' the 'static' link type is selected, in
other case the `dynlib` is selected.

LIBCAPNG_LIB_PATH=<path> will add the <path> directory
to the compiler's library search path (i.e., -L <path>)

Signed-off-by: German Maglione <gmaglione@redhat.com>

2022-03-06 14:53 UTC, alyssais commented
I think it would be better to use pkg-config, so the user doesn't have to manually specify library paths (they'd just set `PKG_CONFIG_ALL_STATIC` if they wanted static builds).  This is the approach lots of other Rust crates take.  I've opened #3 to demonstrate this approach.

2022-03-07 09:48 UTC, germag commented
> I think it would be better to use pkg-config, so the user doesn't have to manually specify library paths (they'd just set `PKG_CONFIG_ALL_STATIC` if they wanted static builds). This is the approach lots of other Rust crates take. I've opened #3 to demonstrate this approach.

Will using pkg-config also allow linking to a libcap-ng compiled from source code (non-system-wide installed)?

2022-03-10 09:19 UTC, germag commented
> Will using pkg-config also allow linking to a libcap-ng compiled from source code (non-system-wide installed)?

I respond to myself, the `pkg-config` crate is just a wrapper for the `pkg-config` tool, so no issues here (idk why I thought it was something else)

2022-03-10 09:42 UTC, germag commented
> I think it would be better to use pkg-config, so the user doesn't have to manually specify library paths (they'd just set `PKG_CONFIG_ALL_STATIC` if they wanted static builds). This is the approach lots of other Rust crates take. I've opened #3 to demonstrate this approach.

Were you able to compile statically in rust:alpine?

2022-03-14 11:20 UTC, alyssais commented
Here's a Dockerfile that builds statically using pkg-config:

```dockerfile
FROM rust:alpine
RUN apk add autoconf automake gperf libc-dev libtool linux-headers make \
    pkgconf python3 wget
RUN wget https://github.com/seccomp/libseccomp/archive/v2.5.3/libseccomp-2.5.3.tar.gz \
    && tar xf libseccomp-2.5.3.tar.gz \
    && cd libseccomp-2.5.3 \
    && autoreconf -i \
    && ./configure --enable-static --disable-shared --prefix=/opt/static \
    && make \
    && make install
RUN wget https://people.redhat.com/sgrubb/libcap-ng/libcap-ng-0.7.10.tar.gz \
    && tar xf libcap-ng-0.7.10.tar.gz \
    && cd libcap-ng-0.7.10 \
    && ./configure --enable-static --disable-shared --prefix=/opt/static \
    && make \
    && make install
RUN wget https://gitlab.com/ghm-virtio-fs/virtiofsd/-/archive/1b583198d62d2acad810b7e89f373280aadbe743/virtiofsd-1b583198d62d2acad810b7e89f373280aadbe743.tar.bz2 \
    && tar xf virtiofsd-1b583198d62d2acad810b7e89f373280aadbe743.tar.bz2
WORKDIR virtiofsd-1b583198d62d2acad810b7e89f373280aadbe743
RUN printf '[patch.crates-io]\ncapng = { git = "https://github.com/alyssais/capng", branch = "pkg-config" }\n' >> Cargo.toml \
    && PKG_CONFIG_ALL_STATIC=1 PKG_CONFIG_PATH=/opt/static/lib/pkgconfig cargo build --target x86_64-unknown-linux-musl
```

I actually hadn't tried this before, which is why I took a little while to respond.  I usually build my virtiofsd with Nix, and had tested all the musl/static stuff that way, since it's what I know.

2022-03-21 17:27 UTC, slp commented
Thank you both, @alyssais and @germag. I've been playing with both #2 and #3. I like the latter more, but I was a bit puzzled that it was able to make link `libseccomp-sys` without passing `LIBSECCOMP_LIB_PATH` nor `LIBSECCOMP_LINK_TYPE`. Turns out that works because both static libraries are placed in the same directory (`/opt/static/lib`), so the extra args added by pkg-config worked for both libraries.

Knowing this, I think I'm more inclined towards merging #2, for consistency with `libseccomp-sys` and to avoid adding an additional dependency.

2022-03-21 17:28 UTC, slp requested changes

2022-03-21 17:28 UTC, slp commented on build.rs
> +const LIBCAPNG_LINK_STATIC: &str = "LIBCAPNG_LINK_STATIC";
For consistency with `libseccomp-sys`, could you please rename this to `LIBSECCOMP_LINK_TYPE` and mimic its behavior?

2022-03-31 10:51 UTC, germag commented
v2:
- Rename the env variable from `LIBCAPNG_LINK_STATIC` to `LIBCAPNG_LINK_TYPE` to be consistent with `libseccomp-sys`

2022-04-04 09:39 UTC, slp commented
LGTM, thanks @germag and @alyssais !

2022-04-04 09:39 UTC, merged